---
version: '3'

services:
  pocketdb:
    build:
      context: ./Dockerfile
    ports:
      - '8080:8080'
    restart: always
    volumes:
      - ./pocketbase/pb_data:/pb_data
    networks:
      - pocketbase

networks:
  pocketbase:
